name: Build Gatsby Site

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
